logging:
  level:
    ROOT: INFO
    org.hibernate.SQL: DEBUG
    org.springframework.security: INFO
    com.ecom.api: DEBUG
    org.apache.hc.client5.http: INFO
    #liquibase: DEBUG

spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
